/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author DAVIDCF
 */



public class FrmPPal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPPal
     */
    public FrmPPal() {
        initComponents();
        cargarCombo(listaAlfolbras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        btnEngadir = new javax.swing.JButton();
        txtCor = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbAlfombra = new javax.swing.JComboBox<>();
        btnInfoAlfombra = new javax.swing.JButton();
        btnEliminarAlfombra = new javax.swing.JButton();
        btnEliminarTodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nova alfombra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel2.setLayout(null);

        jLabel1.setText("Modelo");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 30, 60, 16);

        jLabel2.setText("Cor");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 60, 50, 16);

        jLabel3.setText("Ancho");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 60, 35, 16);
        jPanel2.add(txtModelo);
        txtModelo.setBounds(60, 30, 450, 22);

        btnEngadir.setText("Engadir");
        btnEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirActionPerformed(evt);
            }
        });
        jPanel2.add(btnEngadir);
        btnEngadir.setBounds(530, 30, 140, 22);
        jPanel2.add(txtCor);
        txtCor.setBounds(60, 60, 90, 22);
        jPanel2.add(txtAncho);
        txtAncho.setBounds(220, 60, 64, 22);

        jLabel4.setText("(cm)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(300, 60, 37, 16);

        jLabel5.setText("Alto");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(350, 60, 22, 16);
        jPanel2.add(txtAlto);
        txtAlto.setBounds(400, 60, 64, 22);

        jLabel6.setText("(cm)");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(480, 60, 37, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 680, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alfombras dispoñibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        btnInfoAlfombra.setText("Información da alfombra");
        btnInfoAlfombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoAlfombraActionPerformed(evt);
            }
        });

        btnEliminarAlfombra.setText("Eliminar alfombra");
        btnEliminarAlfombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlfombraActionPerformed(evt);
            }
        });

        btnEliminarTodas.setText("Eliminar todas");
        btnEliminarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAlfombra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInfoAlfombra, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnEliminarAlfombra, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnEliminarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAlfombra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInfoAlfombra)
                        .addComponent(btnEliminarAlfombra))
                    .addComponent(btnEliminarTodas))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 130, 680, 100);

        setSize(new java.awt.Dimension(720, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirActionPerformed
        // TODO add your handling code here:
        
        //COMPROBACIONES DE ENTRADA DE DATOS
        if(txtModelo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta introducir el nombre del modelo");
            return;
        }
        if(txtCor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta introducir a cor");
            return;
        }
        if(txtAncho.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta introducir el ancho");
            return;
        } 
        if(!txtAncho.getText().matches("[0-9]+")){
           JOptionPane.showMessageDialog(this, "El ancho debe ser un numero entero");
           return;
        }
        if(txtAlto.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta introducir el alto");
            return;
        } 
        if(!txtAlto.getText().matches("[0-9]+")){
           JOptionPane.showMessageDialog(this, "El alto debe ser un numero entero");
           return;
        }
       
        //SI LLEGAMOS AQUI LOS DATOS SON CORRECTOS
        
        //Creamos alfombra temporal y la añadimos
        Alfombra a = new Alfombra(txtModelo.getText().trim(), txtCor.getText().trim(), Integer.parseInt(txtAncho.getText().trim()), Integer.parseInt(txtAlto.getText().trim()));  
        listaAlfolbras.add(a);
        //Cargamos combo y limpiamos datos
        cmbAlfombra.removeAllItems();
        cargarCombo(listaAlfolbras);
        limpiarDatos();
    }//GEN-LAST:event_btnEngadirActionPerformed

    private void btnInfoAlfombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoAlfombraActionPerformed
        // TODO add your handling code here:
                
        Alfombra a = (Alfombra) cmbAlfombra.getSelectedItem();
        
        if(a==null){
            JOptionPane.showMessageDialog(this, "Debes seleccionar una alfombra");
        }else{
            JOptionPane.showMessageDialog(this, "MODELO: " + a.getModelo() + "\nCOR: " + a.getCor()+ "\nANCHO: " + a.getAncho()+ "\nALTO: " + a.getAlto());
        }
        
        
        
        
    }//GEN-LAST:event_btnInfoAlfombraActionPerformed

    private void btnEliminarAlfombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlfombraActionPerformed
        // TODO add your handling code here:
        
        Alfombra a = (Alfombra) cmbAlfombra.getSelectedItem();
        
        if(a==null){
            JOptionPane.showMessageDialog(this, "Debes seleccionar una alfombra");
        }else{
            listaAlfolbras.remove(a);
        }
        
        cmbAlfombra.removeAllItems();
        cargarCombo(listaAlfolbras);
        
    }//GEN-LAST:event_btnEliminarAlfombraActionPerformed

    private void btnEliminarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodasActionPerformed
        // TODO add your handling code here:
        
        if(listaAlfolbras.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay alfombras a elminar");
        }else{
            listaAlfolbras.removeAll(listaAlfolbras);
        }
        
        cmbAlfombra.removeAllItems();
    }//GEN-LAST:event_btnEliminarTodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPal().setVisible(true);
            }
        });
    }
    
    List<Alfombra> listaAlfolbras = new ArrayList<>();
    
    
    public void cargarCombo(List<Alfombra> listaAlfombras){
        for (Alfombra a : listaAlfombras) {
            cmbAlfombra.addItem(a);
        }
    }
    
    public void limpiarDatos(){
        txtModelo.setText("");
        txtCor.setText("");
        txtAncho.setText("");
        txtAlto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarAlfombra;
    private javax.swing.JButton btnEliminarTodas;
    private javax.swing.JButton btnEngadir;
    private javax.swing.JButton btnInfoAlfombra;
    private javax.swing.JComboBox<Alfombra> cmbAlfombra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
