/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

/**
 *
 * @author davidcf
 */
public class FrmPPal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPPal
     */
    public FrmPPal() {
        initComponents();
        lstVentanas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnHijaA = new javax.swing.JButton();
        btnHijaB = new javax.swing.JButton();
        btnHijaC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rdoMostrarTipoA = new javax.swing.JRadioButton();
        rdoMostrarTipoB = new javax.swing.JRadioButton();
        rdoMostrarTipoC = new javax.swing.JRadioButton();
        rdoMostrarTodas = new javax.swing.JRadioButton();
        btnMostrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rdoOcultarTipoA = new javax.swing.JRadioButton();
        rdoOcultarTipoB = new javax.swing.JRadioButton();
        rdoOcultarTipoC = new javax.swing.JRadioButton();
        rdoOcultarTodas = new javax.swing.JRadioButton();
        btnOcultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVentanas = new javax.swing.JList<>();
        btnMostrarElemLista = new javax.swing.JButton();
        btnOcultarElemLista = new javax.swing.JButton();
        btnCerrarElemLista = new javax.swing.JButton();
        txtHijosActuales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnHijaA.setText("Hija A");
        btnHijaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijaAActionPerformed(evt);
            }
        });
        getContentPane().add(btnHijaA);
        btnHijaA.setBounds(10, 10, 72, 22);

        btnHijaB.setText("Hija B");
        btnHijaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijaBActionPerformed(evt);
            }
        });
        getContentPane().add(btnHijaB);
        btnHijaB.setBounds(10, 40, 72, 22);

        btnHijaC.setText("Hija C");
        btnHijaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijaCActionPerformed(evt);
            }
        });
        getContentPane().add(btnHijaC);
        btnHijaC.setBounds(10, 70, 72, 22);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rdoMostrarTipoA);
        rdoMostrarTipoA.setText("Tipo A");
        rdoMostrarTipoA.setAlignmentY(0.0F);
        jPanel1.add(rdoMostrarTipoA);

        buttonGroup1.add(rdoMostrarTipoB);
        rdoMostrarTipoB.setText("Tipo B");
        jPanel1.add(rdoMostrarTipoB);

        buttonGroup1.add(rdoMostrarTipoC);
        rdoMostrarTipoC.setText("Tipo C");
        jPanel1.add(rdoMostrarTipoC);

        buttonGroup1.add(rdoMostrarTodas);
        rdoMostrarTodas.setText("Todas");
        jPanel1.add(rdoMostrarTodas);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 10, 110, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ocultar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup2.add(rdoOcultarTipoA);
        rdoOcultarTipoA.setText("Tipo A");
        jPanel2.add(rdoOcultarTipoA);

        buttonGroup2.add(rdoOcultarTipoB);
        rdoOcultarTipoB.setText("Tipo B");
        jPanel2.add(rdoOcultarTipoB);

        buttonGroup2.add(rdoOcultarTipoC);
        rdoOcultarTipoC.setText("Tipo C");
        jPanel2.add(rdoOcultarTipoC);

        buttonGroup2.add(rdoOcultarTodas);
        rdoOcultarTodas.setText("Todas");
        jPanel2.add(rdoOcultarTodas);

        btnOcultar.setText("Ocultar");
        btnOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarActionPerformed(evt);
            }
        });
        jPanel2.add(btnOcultar);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 10, 130, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventanas hijas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jScrollPane1.setViewportView(lstVentanas);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 480, 90);

        btnMostrarElemLista.setText("Mostrar");
        btnMostrarElemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarElemListaActionPerformed(evt);
            }
        });
        jPanel3.add(btnMostrarElemLista);
        btnMostrarElemLista.setBounds(120, 130, 72, 22);

        btnOcultarElemLista.setText("Ocultar");
        btnOcultarElemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarElemListaActionPerformed(evt);
            }
        });
        jPanel3.add(btnOcultarElemLista);
        btnOcultarElemLista.setBounds(210, 130, 72, 22);

        btnCerrarElemLista.setText("Cerrar");
        btnCerrarElemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarElemListaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCerrarElemLista);
        btnCerrarElemLista.setBounds(300, 130, 72, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(370, 10, 520, 170);
        getContentPane().add(txtHijosActuales);
        txtHijosActuales.setBounds(190, 200, 200, 30);

        setSize(new java.awt.Dimension(924, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHijaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijaAActionPerformed
        // TODO add your handling code here:

        VentanaTipoA vA = new VentanaTipoA(contadorVentana, this, false);
        vA.setVisible(true);
        listaVentanas.add(vA);
        modelo.addElement(vA);
        txtHijosActuales.setText("Numero de hijos actuales: " + contadorVentana);
        contadorVentana++;

    }//GEN-LAST:event_btnHijaAActionPerformed

    private void btnHijaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijaBActionPerformed
        // TODO add your handling code here:
        VentanaTipoB vB = new VentanaTipoB(contadorVentana, this, false);
        vB.setVisible(true);
        listaVentanas.add(vB);
        modelo.addElement(vB);
        txtHijosActuales.setText("Numero de hijos actuales: " + contadorVentana);
        contadorVentana++;
    }//GEN-LAST:event_btnHijaBActionPerformed

    private void btnHijaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijaCActionPerformed
        // TODO add your handling code here:
        VentanaTipoC vC = new VentanaTipoC(contadorVentana, this, false);
        vC.setVisible(true);
        listaVentanas.add(vC);
        modelo.addElement(vC);
        txtHijosActuales.setText("Numero de hijos actuales: " + contadorVentana);
        contadorVentana++;
    }//GEN-LAST:event_btnHijaCActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:

        if (rdoMostrarTipoA.isSelected()) {
            for (JDialog v : listaVentanas) {
                if (v instanceof VentanaTipoA) {
                    v.setVisible(true);
                }
            }
        }
        
        if (rdoMostrarTipoB.isSelected()) {
            for (JDialog v : listaVentanas) {
                if (v instanceof VentanaTipoB) {
                    v.setVisible(true);
                }
            }
        }
        
        if (rdoMostrarTipoC.isSelected()) {
            for (JDialog v : listaVentanas) {
                if (v instanceof VentanaTipoC) {
                    v.setVisible(true);
                }
            }
        }
        
        if (rdoMostrarTodas.isSelected()) {
            for (JDialog v : listaVentanas) {
                v.setVisible(true);
            }
        }
        
        actualizarModelo();


    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarActionPerformed
        // TODO add your handling code here:
        if(rdoOcultarTipoA.isSelected()){
            for (JDialog v : listaVentanas) {
                if(v instanceof VentanaTipoA){
                    v.setVisible(false);
                }
            }
        }
        
        if(rdoOcultarTipoB.isSelected()){
            for (JDialog v : listaVentanas) {
                if(v instanceof VentanaTipoB){
                    v.setVisible(false);
                }
            }
        }
        if(rdoOcultarTipoC.isSelected()){
            for (JDialog v : listaVentanas) {
                if(v instanceof VentanaTipoC){
                    v.setVisible(false);
                }
            }
        }
        if(rdoOcultarTodas.isSelected()){
            for (JDialog v : listaVentanas) {
                    v.setVisible(false);
            }
        }
        
        actualizarModelo();
    }//GEN-LAST:event_btnOcultarActionPerformed

    private void btnMostrarElemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarElemListaActionPerformed
        // TODO add your handling code here:
        List<JDialog> ventanas = lstVentanas.getSelectedValuesList();
        
        for (JDialog v : ventanas) {
            v.setVisible(true);
        }
        
    }//GEN-LAST:event_btnMostrarElemListaActionPerformed

    private void btnOcultarElemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarElemListaActionPerformed
        // TODO add your handling code here:
        List<JDialog> ventanas = lstVentanas.getSelectedValuesList();
        
        for (JDialog v : ventanas) {
            v.setVisible(false);
        }
    }//GEN-LAST:event_btnOcultarElemListaActionPerformed

    private void btnCerrarElemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarElemListaActionPerformed
        // TODO add your handling code here:
        List<JDialog> ventanas = lstVentanas.getSelectedValuesList();
        
        for (JDialog v : ventanas) {
            v.setVisible(false);
            listaVentanas.remove(v);            
            actualizarModelo();
        }
    }//GEN-LAST:event_btnCerrarElemListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPal().setVisible(true);
            }
        });
    }

    int contadorVentana = 1;
    List<JDialog> listaVentanas = new ArrayList<>();
    private DefaultListModel<JDialog> modelo = new DefaultListModel<>();
    
    private void actualizarModelo(){
        modelo.removeAllElements();
        modelo.addAll(listaVentanas);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarElemLista;
    private javax.swing.JButton btnHijaA;
    private javax.swing.JButton btnHijaB;
    private javax.swing.JButton btnHijaC;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrarElemLista;
    private javax.swing.JButton btnOcultar;
    private javax.swing.JButton btnOcultarElemLista;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<JDialog> lstVentanas;
    private javax.swing.JRadioButton rdoMostrarTipoA;
    private javax.swing.JRadioButton rdoMostrarTipoB;
    private javax.swing.JRadioButton rdoMostrarTipoC;
    private javax.swing.JRadioButton rdoMostrarTodas;
    private javax.swing.JRadioButton rdoOcultarTipoA;
    private javax.swing.JRadioButton rdoOcultarTipoB;
    private javax.swing.JRadioButton rdoOcultarTipoC;
    private javax.swing.JRadioButton rdoOcultarTodas;
    private javax.swing.JLabel txtHijosActuales;
    // End of variables declaration//GEN-END:variables
}
