/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;

import Ejercicio1.*;

/**
 *
 * @author davidcf
 */
public class FrmPPal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPPal
     */
    public FrmPPal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWest = new javax.swing.JPanel();
        pnlNorth = new javax.swing.JPanel();
        pnlSouth = new javax.swing.JPanel();
        pnlEast = new javax.swing.JPanel();
        pnlNorth1 = new javax.swing.JPanel();
        pnlSouth1 = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        pnlNorth2 = new javax.swing.JPanel();
        pnlWest3 = new javax.swing.JPanel();
        pnlEast3 = new javax.swing.JPanel();
        pnlCenter3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlWest2 = new javax.swing.JPanel();
        pnlCenter2 = new javax.swing.JPanel();
        pnlNorth4 = new javax.swing.JPanel();
        pnlSouth4 = new javax.swing.JPanel();
        pnlCenter4 = new javax.swing.JPanel();
        pnlNorth5 = new javax.swing.JPanel();
        pnlCenter5 = new javax.swing.JPanel();
        pnlSouth5 = new javax.swing.JPanel();
        pnlWest5 = new javax.swing.JPanel();
        pnlEast5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UD1.PRACTICA4_DAVID");

        pnlWest.setBackground(new java.awt.Color(255, 255, 0));
        pnlWest.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout pnlWestLayout = new javax.swing.GroupLayout(pnlWest);
        pnlWest.setLayout(pnlWestLayout);
        pnlWestLayout.setHorizontalGroup(
            pnlWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlWestLayout.setVerticalGroup(
            pnlWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnlWest, java.awt.BorderLayout.WEST);

        pnlNorth.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlNorth, java.awt.BorderLayout.NORTH);

        pnlSouth.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSouthLayout = new javax.swing.GroupLayout(pnlSouth);
        pnlSouth.setLayout(pnlSouthLayout);
        pnlSouthLayout.setHorizontalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        pnlSouthLayout.setVerticalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlSouth, java.awt.BorderLayout.SOUTH);

        pnlEast.setBackground(new java.awt.Color(102, 102, 255));
        pnlEast.setLayout(new java.awt.BorderLayout());

        pnlNorth1.setBackground(new java.awt.Color(51, 51, 255));
        pnlNorth1.setMinimumSize(new java.awt.Dimension(100, 0));
        pnlNorth1.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout pnlNorth1Layout = new javax.swing.GroupLayout(pnlNorth1);
        pnlNorth1.setLayout(pnlNorth1Layout);
        pnlNorth1Layout.setHorizontalGroup(
            pnlNorth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlNorth1Layout.setVerticalGroup(
            pnlNorth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlEast.add(pnlNorth1, java.awt.BorderLayout.CENTER);

        pnlSouth1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout pnlSouth1Layout = new javax.swing.GroupLayout(pnlSouth1);
        pnlSouth1.setLayout(pnlSouth1Layout);
        pnlSouth1Layout.setHorizontalGroup(
            pnlSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlSouth1Layout.setVerticalGroup(
            pnlSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlEast.add(pnlSouth1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlEast, java.awt.BorderLayout.EAST);

        pnlCenter.setBackground(new java.awt.Color(204, 204, 204));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlNorth2.setBackground(new java.awt.Color(51, 51, 51));
        pnlNorth2.setMinimumSize(new java.awt.Dimension(0, 40));
        pnlNorth2.setPreferredSize(new java.awt.Dimension(0, 40));
        pnlNorth2.setLayout(new java.awt.BorderLayout());

        pnlWest3.setBackground(new java.awt.Color(0, 204, 204));
        pnlWest3.setMinimumSize(new java.awt.Dimension(20, 0));
        pnlWest3.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout pnlWest3Layout = new javax.swing.GroupLayout(pnlWest3);
        pnlWest3.setLayout(pnlWest3Layout);
        pnlWest3Layout.setHorizontalGroup(
            pnlWest3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlWest3Layout.setVerticalGroup(
            pnlWest3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNorth2.add(pnlWest3, java.awt.BorderLayout.WEST);

        pnlEast3.setBackground(new java.awt.Color(51, 51, 51));
        pnlEast3.setMinimumSize(new java.awt.Dimension(20, 0));
        pnlEast3.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout pnlEast3Layout = new javax.swing.GroupLayout(pnlEast3);
        pnlEast3.setLayout(pnlEast3Layout);
        pnlEast3Layout.setHorizontalGroup(
            pnlEast3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlEast3Layout.setVerticalGroup(
            pnlEast3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNorth2.add(pnlEast3, java.awt.BorderLayout.EAST);

        pnlCenter3.setBackground(new java.awt.Color(0, 0, 0));
        pnlCenter3.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlCenter3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("ATRAS");
        pnlCenter3.add(jButton1);

        jButton2.setText("MENU");
        pnlCenter3.add(jButton2);

        jButton3.setText("SIGUIENTE");
        pnlCenter3.add(jButton3);

        pnlNorth2.add(pnlCenter3, java.awt.BorderLayout.CENTER);

        pnlCenter.add(pnlNorth2, java.awt.BorderLayout.NORTH);

        pnlWest2.setBackground(new java.awt.Color(204, 204, 0));
        pnlWest2.setMinimumSize(new java.awt.Dimension(150, 0));
        pnlWest2.setPreferredSize(new java.awt.Dimension(150, 0));

        javax.swing.GroupLayout pnlWest2Layout = new javax.swing.GroupLayout(pnlWest2);
        pnlWest2.setLayout(pnlWest2Layout);
        pnlWest2Layout.setHorizontalGroup(
            pnlWest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnlWest2Layout.setVerticalGroup(
            pnlWest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlWest2, java.awt.BorderLayout.WEST);

        pnlCenter2.setBackground(new java.awt.Color(204, 204, 204));
        pnlCenter2.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlCenter2.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlCenter2.setLayout(new java.awt.BorderLayout());

        pnlNorth4.setBackground(new java.awt.Color(204, 0, 0));
        pnlNorth4.setMinimumSize(new java.awt.Dimension(0, 40));
        pnlNorth4.setPreferredSize(new java.awt.Dimension(0, 40));

        javax.swing.GroupLayout pnlNorth4Layout = new javax.swing.GroupLayout(pnlNorth4);
        pnlNorth4.setLayout(pnlNorth4Layout);
        pnlNorth4Layout.setHorizontalGroup(
            pnlNorth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlNorth4Layout.setVerticalGroup(
            pnlNorth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter2.add(pnlNorth4, java.awt.BorderLayout.NORTH);

        pnlSouth4.setBackground(new java.awt.Color(51, 255, 255));
        pnlSouth4.setMinimumSize(new java.awt.Dimension(0, 40));
        pnlSouth4.setPreferredSize(new java.awt.Dimension(0, 40));

        javax.swing.GroupLayout pnlSouth4Layout = new javax.swing.GroupLayout(pnlSouth4);
        pnlSouth4.setLayout(pnlSouth4Layout);
        pnlSouth4Layout.setHorizontalGroup(
            pnlSouth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSouth4Layout.setVerticalGroup(
            pnlSouth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter2.add(pnlSouth4, java.awt.BorderLayout.SOUTH);

        pnlCenter4.setBackground(new java.awt.Color(204, 204, 204));
        pnlCenter4.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlCenter4.setLayout(new java.awt.BorderLayout());

        pnlNorth5.setBackground(new java.awt.Color(255, 255, 51));
        pnlNorth5.setMinimumSize(new java.awt.Dimension(0, 80));
        pnlNorth5.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout pnlNorth5Layout = new javax.swing.GroupLayout(pnlNorth5);
        pnlNorth5.setLayout(pnlNorth5Layout);
        pnlNorth5Layout.setHorizontalGroup(
            pnlNorth5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlNorth5Layout.setVerticalGroup(
            pnlNorth5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter4.add(pnlNorth5, java.awt.BorderLayout.NORTH);

        pnlCenter5.setBackground(new java.awt.Color(255, 0, 51));
        pnlCenter5.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pnlCenter5Layout = new javax.swing.GroupLayout(pnlCenter5);
        pnlCenter5.setLayout(pnlCenter5Layout);
        pnlCenter5Layout.setHorizontalGroup(
            pnlCenter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        pnlCenter5Layout.setVerticalGroup(
            pnlCenter5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        pnlCenter4.add(pnlCenter5, java.awt.BorderLayout.CENTER);

        pnlSouth5.setBackground(new java.awt.Color(153, 153, 255));
        pnlSouth5.setMinimumSize(new java.awt.Dimension(0, 80));
        pnlSouth5.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout pnlSouth5Layout = new javax.swing.GroupLayout(pnlSouth5);
        pnlSouth5.setLayout(pnlSouth5Layout);
        pnlSouth5Layout.setHorizontalGroup(
            pnlSouth5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        pnlSouth5Layout.setVerticalGroup(
            pnlSouth5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnlCenter4.add(pnlSouth5, java.awt.BorderLayout.SOUTH);

        pnlWest5.setBackground(new java.awt.Color(204, 204, 255));
        pnlWest5.setMinimumSize(new java.awt.Dimension(80, 0));
        pnlWest5.setPreferredSize(new java.awt.Dimension(80, 0));

        javax.swing.GroupLayout pnlWest5Layout = new javax.swing.GroupLayout(pnlWest5);
        pnlWest5.setLayout(pnlWest5Layout);
        pnlWest5Layout.setHorizontalGroup(
            pnlWest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlWest5Layout.setVerticalGroup(
            pnlWest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenter4.add(pnlWest5, java.awt.BorderLayout.WEST);

        pnlEast5.setBackground(new java.awt.Color(255, 255, 255));
        pnlEast5.setMinimumSize(new java.awt.Dimension(80, 0));
        pnlEast5.setPreferredSize(new java.awt.Dimension(80, 0));

        javax.swing.GroupLayout pnlEast5Layout = new javax.swing.GroupLayout(pnlEast5);
        pnlEast5.setLayout(pnlEast5Layout);
        pnlEast5Layout.setHorizontalGroup(
            pnlEast5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pnlEast5Layout.setVerticalGroup(
            pnlEast5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        pnlCenter4.add(pnlEast5, java.awt.BorderLayout.EAST);

        pnlCenter2.add(pnlCenter4, java.awt.BorderLayout.CENTER);

        pnlCenter.add(pnlCenter2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 781, 552);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCenter2;
    private javax.swing.JPanel pnlCenter3;
    private javax.swing.JPanel pnlCenter4;
    private javax.swing.JPanel pnlCenter5;
    private javax.swing.JPanel pnlEast;
    private javax.swing.JPanel pnlEast3;
    private javax.swing.JPanel pnlEast5;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlNorth1;
    private javax.swing.JPanel pnlNorth2;
    private javax.swing.JPanel pnlNorth4;
    private javax.swing.JPanel pnlNorth5;
    private javax.swing.JPanel pnlSouth;
    private javax.swing.JPanel pnlSouth1;
    private javax.swing.JPanel pnlSouth4;
    private javax.swing.JPanel pnlSouth5;
    private javax.swing.JPanel pnlWest;
    private javax.swing.JPanel pnlWest2;
    private javax.swing.JPanel pnlWest3;
    private javax.swing.JPanel pnlWest5;
    // End of variables declaration//GEN-END:variables
}
