/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio4;

/**
 *
 * @author davidcf
 */
public class FrmPPal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPPal
     */
    public FrmPPal() {
        initComponents();
        pnlAmarillo.setVisible(false);
        pnlAzul.setVisible(false);
        pnlVerde.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlLeft = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        rdoAzul = new javax.swing.JRadioButton();
        rdoVerde = new javax.swing.JRadioButton();
        rdoAmarillo = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlCenter = new javax.swing.JPanel();
        pnlAzul = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        pnlVerde = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        pnlAmarillo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLeft.setBackground(new java.awt.Color(153, 153, 255));
        pnlLeft.setMaximumSize(new java.awt.Dimension(200, 0));
        pnlLeft.setMinimumSize(new java.awt.Dimension(200, 0));
        pnlLeft.setPreferredSize(new java.awt.Dimension(200, 0));
        pnlLeft.setLayout(new javax.swing.BoxLayout(pnlLeft, javax.swing.BoxLayout.PAGE_AXIS));
        pnlLeft.add(filler1);

        buttonGroup1.add(rdoAzul);
        rdoAzul.setText("Azul");
        rdoAzul.setAlignmentX(0.5F);
        rdoAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAzulActionPerformed(evt);
            }
        });
        pnlLeft.add(rdoAzul);

        buttonGroup1.add(rdoVerde);
        rdoVerde.setText("Verde");
        rdoVerde.setAlignmentX(0.5F);
        rdoVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoVerdeActionPerformed(evt);
            }
        });
        pnlLeft.add(rdoVerde);

        buttonGroup1.add(rdoAmarillo);
        rdoAmarillo.setText("Amarillo");
        rdoAmarillo.setAlignmentX(0.5F);
        rdoAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAmarilloActionPerformed(evt);
            }
        });
        pnlLeft.add(rdoAmarillo);
        pnlLeft.add(filler2);

        getContentPane().add(pnlLeft, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(204, 255, 153));

        pnlAzul.setBackground(new java.awt.Color(51, 153, 255));
        pnlAzul.setLayout(new javax.swing.BoxLayout(pnlAzul, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButton1.setText("jRadioButton1");
        pnlAzul.add(jRadioButton1);

        jRadioButton2.setText("jRadioButton2");
        pnlAzul.add(jRadioButton2);

        jRadioButton3.setText("jRadioButton3");
        pnlAzul.add(jRadioButton3);

        jRadioButton4.setText("jRadioButton4");
        pnlAzul.add(jRadioButton4);

        jRadioButton5.setText("jRadioButton5");
        pnlAzul.add(jRadioButton5);

        pnlVerde.setBackground(new java.awt.Color(102, 255, 102));
        pnlVerde.setLayout(new javax.swing.BoxLayout(pnlVerde, javax.swing.BoxLayout.LINE_AXIS));

        jCheckBox1.setText("jCheckBox1");
        pnlVerde.add(jCheckBox1);

        jCheckBox2.setText("jCheckBox2");
        pnlVerde.add(jCheckBox2);

        jCheckBox3.setText("jCheckBox3");
        pnlVerde.add(jCheckBox3);

        jCheckBox4.setText("jCheckBox4");
        pnlVerde.add(jCheckBox4);

        pnlAmarillo.setBackground(new java.awt.Color(255, 255, 102));
        pnlAmarillo.setLayout(new javax.swing.BoxLayout(pnlAmarillo, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("jButton1");
        pnlAmarillo.add(jButton1);

        jButton2.setText("jButton2");
        pnlAmarillo.add(jButton2);

        jButton3.setText("jButton3");
        pnlAmarillo.add(jButton3);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCenterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCenterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCenterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCenterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(752, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAzulActionPerformed
        // TODO add your handling code here:
        pnlAzul.setVisible(true);
        pnlAmarillo.setVisible(false);
        pnlVerde.setVisible(false);
    }//GEN-LAST:event_rdoAzulActionPerformed

    private void rdoVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoVerdeActionPerformed
        // TODO add your handling code here:
        pnlVerde.setVisible(true);
        pnlAzul.setVisible(false);
        pnlAmarillo.setVisible(false);
    }//GEN-LAST:event_rdoVerdeActionPerformed

    private void rdoAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAmarilloActionPerformed
        // TODO add your handling code here:
        pnlAmarillo.setVisible(true);
        pnlVerde.setVisible(false);
        pnlAzul.setVisible(false);
    }//GEN-LAST:event_rdoAmarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel pnlAmarillo;
    private javax.swing.JPanel pnlAzul;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlVerde;
    private javax.swing.JRadioButton rdoAmarillo;
    private javax.swing.JRadioButton rdoAzul;
    private javax.swing.JRadioButton rdoVerde;
    // End of variables declaration//GEN-END:variables
}
