/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author davidcf
 */
public class FrmPPal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPPal
     */
    public FrmPPal() {
        initComponents();
        lstAlfombras.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAncho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAlfombras = new javax.swing.JList<>();
        btnInfomacion = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminarTodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UD1.PRACTICA3.EJERCICIO1");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nova alfombra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel1.setLayout(null);

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(11, 34, 57, 16);

        jLabel2.setText("Cor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(11, 68, 28, 16);
        jPanel1.add(txtModelo);
        txtModelo.setBounds(74, 31, 454, 22);
        jPanel1.add(txtCor);
        txtCor.setBounds(74, 65, 98, 22);

        jLabel3.setText("Ancho");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 68, 45, 16);
        jPanel1.add(txtAncho);
        txtAncho.setBounds(241, 65, 70, 22);

        jLabel4.setText("(cm)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(323, 68, 34, 16);

        jLabel5.setText("Alto");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(369, 68, 45, 16);
        jPanel1.add(txtAlto);
        txtAlto.setBounds(420, 65, 64, 22);

        jLabel6.setText("(cm)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(502, 68, 34, 16);

        btnAñadir.setText("Engadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir);
        btnAñadir.setBounds(546, 31, 163, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 730, 110);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alfombras disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel2.setLayout(null);

        jScrollPane1.setViewportView(lstAlfombras);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(11, 25, 378, 184);

        btnInfomacion.setText("Informacion das alfombras");
        btnInfomacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfomacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnInfomacion);
        btnInfomacion.setBounds(407, 25, 302, 22);

        btnEliminar.setText("Eliminar alfombra");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);
        btnEliminar.setBounds(407, 59, 302, 22);

        btnEliminarTodas.setText("Eliminar todas");
        btnEliminarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodasActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarTodas);
        btnEliminarTodas.setBounds(407, 93, 302, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 140, 720, 220);

        setSize(new java.awt.Dimension(767, 418));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
        
        //COMPROBACION DE CAMPOS
        if(txtModelo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes indicar el nombre");
            return;
        }
        
        if(txtCor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes indicar el color");
            return;
        }
        
        if(txtAncho.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes indicar el ancho");
            return;
        }else{
            if(!txtAncho.getText().matches("[0-9]+")){
                JOptionPane.showMessageDialog(this, "El ancho debe ser numérico");
                return;
            }
        }
        
        if(txtAlto.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes indicar el alto");
            return;
        }else{
            if(!txtAlto.getText().matches("[0-9]+")){
                JOptionPane.showMessageDialog(this, "El alto debe ser numérico");
                return;
            }
        }
        
        //SI LOS DATOS SON CORRECTOS, SEGUIMOS.
        
        //AÑADIMOS ALFOMBRA AL MODELO
        modelo.addElement(new Alfombra(txtModelo.getText(), txtCor.getText(), Integer.parseInt(txtAncho.getText()), Integer.parseInt(txtAlto.getText())));
        
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnInfomacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfomacionActionPerformed
        // TODO add your handling code here:
        
        StringBuilder sb = new StringBuilder();
        
        //COMPROBAMOS SI SE HA SELECIONADO NINGUNA O UNA O VARIAS ALFOMBRAS
        if(lstAlfombras.getSelectedIndices().length==0){
            JOptionPane.showMessageDialog(this, "Debes seleccionar las alfombras a mostrar");
        }else{
            
            for (int i = 0; i < lstAlfombras.getSelectedIndices().length; i++) {
                
                Alfombra a = modelo.getElementAt(i);
                
                sb.append("MODELO: " + a.getModelo() + "\nCOR: " + a.getCor() + "\nANCHO: " + a.getAncho() + "\nALTO: " + a.getAncho() + "\n\n");
                
            }
            
            JOptionPane.showMessageDialog(this, sb);
            
        }
        
    }//GEN-LAST:event_btnInfomacionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        //COMPROBAMOS SI SE HA SELECIONADO NINGUNA O UNA O VARIAS ALFOMBRAS
        if(lstAlfombras.getSelectedIndices().length==0){
            JOptionPane.showMessageDialog(this, "Debes selecionar la alfombra a eliminar");
        }else if(lstAlfombras.getSelectedIndices().length>1){
            JOptionPane.showMessageDialog(this, "Solo puedes seleccionar una alfombra de cada vez");
        }else{
            modelo.removeElementAt(lstAlfombras.getSelectedIndex());
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodasActionPerformed
        // TODO add your handling code here:
        
        //COMPROBAMOS SI HAY ALFOMBRAS EN EL MODELO, SI HAY SE ELIMINAN TODAS
        if(modelo.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay alfombras a eliminar");
        }else{
            modelo.removeAllElements();
        }
        
    }//GEN-LAST:event_btnEliminarTodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPal().setVisible(true);
            }
        });
    }
    
    private DefaultListModel<Alfombra> modelo = new DefaultListModel<Alfombra>();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTodas;
    private javax.swing.JButton btnInfomacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Alfombra> lstAlfombras;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}

/*
PASOS TRABAJAR LISTAS

1º crear DefaultListModel<Alfombra> modelo
2º configurar la lista del tipo objeto Alfombra
3º ligar en el constructor la lista nuestra con el modelo creado

*/