/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ejercicio1;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author davidcf
 */
public class NuevoCliente extends javax.swing.JDialog {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApel1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApel2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTlf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("DNI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 40, 16);
        getContentPane().add(txtDNI);
        txtDNI.setBounds(90, 20, 300, 22);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 60, 16);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(90, 50, 300, 22);

        jLabel3.setText("Apellido 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 16);
        getContentPane().add(txtApel1);
        txtApel1.setBounds(90, 80, 300, 22);

        jLabel4.setText("Apellido 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 60, 16);
        getContentPane().add(txtApel2);
        txtApel2.setBounds(90, 110, 300, 22);

        jLabel5.setText("Tlf.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 30, 16);
        getContentPane().add(txtTlf);
        txtTlf.setBounds(90, 140, 300, 22);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 180, 80, 22);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 180, 80, 22);

        setSize(new java.awt.Dimension(426, 265));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                
        //COMPROBACIONES
        
        StringBuilder sb = new StringBuilder("Se han producidos los siguientes errores:\n");
        boolean formularioOK = true;
        
        if(txtDNI.getText().trim().isEmpty()){
            sb.append("- Falta indicar el DNI\n");
            formularioOK = false;
        }
        if(txtNombre.getText().trim().isEmpty()){
            sb.append("- Falta indicar el Nombre\n");
            formularioOK = false;
        }
        if(txtApel1.getText().trim().isEmpty()){
            sb.append("- Falta indicar el primer apellido\n");
            formularioOK = false;
        }
        if(txtApel2.getText().trim().isEmpty()){
            sb.append("- Falta indicar el segundo apellido\n");
            formularioOK = false;
        }
        if(txtTlf.getText().trim().isEmpty()){
            sb.append("- Falta indicar el telefono\n");
            formularioOK = false;
        }
        
        if(formularioOK == false){
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        
        
        //CONSULTA BASE DATOS de Inserccion de datos
        
        String consulta = "INSERT INTO CLIENTES VALUES (?,?,?,?,?)";
        
        try (PreparedStatement sentencia = Conexion.getCon().prepareStatement(consulta)){
            
            sentencia.setString(1, txtDNI.getText());
            sentencia.setString(2, txtNombre.getText());
            sentencia.setString(3, txtApel1.getText());
            sentencia.setString(4, txtApel2.getText());
            sentencia.setString(5, txtTlf.getText());
            
            sentencia.executeUpdate();
        
        } catch (SQLIntegrityConstraintViolationException e){ //EN EL PRIMER CATCH ME ASEGURO DE MOSTRAR AVISO DE CLAVE DUPLICADA AL USUARIO
            JOptionPane.showMessageDialog(this, "El DNI ya está registrado en la BD");
        } catch (SQLException ex) {
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            System.out.println("Error: " + e);
        } finally {
            //Si esta abierta la ventana de bajacliente o altafiesta recargo combos en tiempo real.
            ((FrmPPal)getOwner()).actualizarCombosAltaFiestaBajaCliente();
        }
        
        //LIMPIAR DATOS
        txtDNI.setText("");
        txtNombre.setText("");
        txtApel1.setText("");
        txtApel2.setText("");
        txtTlf.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ((FrmPPal)getOwner()).listaVentanas.remove(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ((FrmPPal)getOwner()).listaVentanas.remove(this);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoCliente dialog = new NuevoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtApel1;
    private javax.swing.JTextField txtApel2;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTlf;
    // End of variables declaration//GEN-END:variables
}
